theme: jekyll-theme-minimal
title: Juan Manuel Pérez
description: Postdoctoral researcher @ Instituto de Cs. de la Computación, FCEN-UBA. Professor @ Maestría Cs. de Datos, UdeSA
logo: files/jmperez.png
